INSERT INTO TBL_TIPO_BITACORA(TIPO_BITACORA) VALUES ("Inicio de Sesion");
INSERT INTO TBL_TIPO_BITACORA(TIPO_BITACORA) VALUES ("Cierre de Sesion");
INSERT INTO TBL_TIPO_BITACORA(TIPO_BITACORA) VALUES ("Inserta Nuevo Usuario");
INSERT INTO TBL_TIPO_BITACORA(TIPO_BITACORA) VALUES ("Modifica Nuevo Usuario");
INSERT INTO TBL_TIPO_BITACORA(TIPO_BITACORA) VALUES ("Elimina un usuario");

INSERT INTO TBL_CARGOS(CARGO , DESCRIPCION) VALUES ("Admin","Permiso global en la aplicacion");
INSERT INTO TBL_CARGOS(CARGO , DESCRIPCION) VALUES ("Normal","Permiso limitado en la aplicacion");