-- MySQL Script generated by MySQL Workbench
-- Sat Jun  6 21:29:10 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rest-api-usuarios
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rest-api-usuarios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rest-api-usuarios` DEFAULT CHARACTER SET utf8 ;
USE `rest-api-usuarios` ;

-- -----------------------------------------------------
-- Table `rest-api-usuarios`.`TBL_CARGOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest-api-usuarios`.`TBL_CARGOS` (
  `ID_CARGO` INT NOT NULL AUTO_INCREMENT,
  `CARGO` VARCHAR(45) NOT NULL,
  `DESCRIPCION` VARCHAR(150) NULL,
  PRIMARY KEY (`ID_CARGO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest-api-usuarios`.`TBL_USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest-api-usuarios`.`TBL_USUARIOS` (
  `ID_USUARIO` INT NOT NULL AUTO_INCREMENT,
  `ID_CARGO` INT NOT NULL,
  `NOMBRE_USUARIO` VARCHAR(45) NOT NULL,
  `APELLIDO_USUARIO` VARCHAR(45) NOT NULL,
  `FECHA_NACIMIENTO` VARCHAR(45) NOT NULL,
  `EMAIL_USUARIO` VARCHAR(45) NOT NULL,
  `PASSWORD_USUARIO` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID_USUARIO`),
  INDEX `fk_TBL_USUARIOS_TBL_CARGOS_idx` (`ID_CARGO` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_USUARIOS_TBL_CARGOS`
    FOREIGN KEY (`ID_CARGO`)
    REFERENCES `rest-api-usuarios`.`TBL_CARGOS` (`ID_CARGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest-api-usuarios`.`TBL_TIPO_BITACORA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest-api-usuarios`.`TBL_TIPO_BITACORA` (
  `ID_TIPO_BITACORA` INT NOT NULL AUTO_INCREMENT,
  `TIPO_BITACORA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_TIPO_BITACORA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest-api-usuarios`.`TBL_BITACORAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest-api-usuarios`.`TBL_BITACORAS` (
  `ID_BITACAORA` INT NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` INT NOT NULL,
  `ID_TIPO_BITACORA` INT NOT NULL,
  `FECHA_HORA_BITACORA` DATETIME NOT NULL,
  PRIMARY KEY (`ID_BITACAORA`),
  INDEX `fk_TBL_BITACORAS_TBL_USUARIOS1_idx` (`ID_USUARIO` ASC) VISIBLE,
  INDEX `fk_TBL_BITACORAS_TBL_TIPO_BITACORA1_idx` (`ID_TIPO_BITACORA` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_BITACORAS_TBL_USUARIOS1`
    FOREIGN KEY (`ID_USUARIO`)
    REFERENCES `rest-api-usuarios`.`TBL_USUARIOS` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_BITACORAS_TBL_TIPO_BITACORA1`
    FOREIGN KEY (`ID_TIPO_BITACORA`)
    REFERENCES `rest-api-usuarios`.`TBL_TIPO_BITACORA` (`ID_TIPO_BITACORA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
