-- MySQL Script generated by MySQL Workbench
-- Thu Sep 17 23:56:26 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema api-db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema api-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `api-db` DEFAULT CHARACTER SET utf8 ;
USE `api-db` ;

-- -----------------------------------------------------
-- Table `api-db`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api-db`.`articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `articleName` VARCHAR(45) NULL,
  `articleDescription` VARCHAR(150) NULL,
  `price` DECIMAL(8,4) NULL,
  `stock` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
