-- MySQL Script generated by MySQL Workbench
-- Thu Nov 12 15:17:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema 00-articles-register-api-php
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 00-articles-register-api-php
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `00-articles-register-api-php` DEFAULT CHARACTER SET utf8 ;
USE `00-articles-register-api-php` ;

-- -----------------------------------------------------
-- Table `00-articles-register-api-php`.`article_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `00-articles-register-api-php`.`article_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `article_type` VARCHAR(45) NOT NULL,
  `description` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `00-articles-register-api-php`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `00-articles-register-api-php`.`articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `article_type_id` INT NOT NULL,
  `article_name` VARCHAR(45) NOT NULL,
  `article_price` DECIMAL(8,2) NOT NULL,
  `article_stock` INT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_articles_article_type_idx` (`article_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_articles_article_type`
    FOREIGN KEY (`article_type_id`)
    REFERENCES `00-articles-register-api-php`.`article_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
