-- MySQL Script generated by MySQL Workbench
-- Tue Oct 27 13:59:11 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tbl_genders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_genders` (
  `gender_id` INT NOT NULL AUTO_INCREMENT,
  `gender_name` VARCHAR(45) NULL,
  `abrev` VARCHAR(45) NULL,
  PRIMARY KEY (`gender_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_soft_delete_options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_soft_delete_options` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `soft_delete_option` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `gender_id` INT NOT NULL,
  `soft_delete_options_id` INT NOT NULL,
  `first_name` VARCHAR(60) NOT NULL,
  `last_name` VARCHAR(60) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  `deleted_at` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_tbl_users_tbl_genders_idx` (`gender_id` ASC) VISIBLE,
  INDEX `fk_tbl_users_tbl_soft_delete_options1_idx` (`soft_delete_options_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_users_tbl_genders`
    FOREIGN KEY (`gender_id`)
    REFERENCES `mydb`.`tbl_genders` (`gender_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_users_tbl_soft_delete_options1`
    FOREIGN KEY (`soft_delete_options_id`)
    REFERENCES `mydb`.`tbl_soft_delete_options` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_masters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_masters` (
  `master_id` INT NOT NULL,
  `role` VARCHAR(60) NOT NULL,
  `salary` DECIMAL(8,2) NOT NULL,
  INDEX `fk_tbl_masters_tbl_users1_idx` (`master_id` ASC) VISIBLE,
  PRIMARY KEY (`master_id`),
  CONSTRAINT `fk_tbl_masters_tbl_users1`
    FOREIGN KEY (`master_id`)
    REFERENCES `mydb`.`tbl_users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_students` (
  `student_id` INT NOT NULL,
  `career` INT NOT NULL,
  `average` DECIMAL(3,1) NULL,
  INDEX `fk_tbl_students_tbl_users1_idx` (`student_id` ASC) VISIBLE,
  PRIMARY KEY (`student_id`),
  CONSTRAINT `fk_tbl_students_tbl_users1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`tbl_users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_logs_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_logs_types` (
  `id_log_type` INT NOT NULL AUTO_INCREMENT,
  `log_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_log_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_logs` (
  `log_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `id_log_type` INT NOT NULL,
  `created_log_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`log_id`),
  INDEX `fk_tbl_logs_tbl_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_tbl_logs_tbl_logs_types1_idx` (`id_log_type` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_logs_tbl_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`tbl_users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_logs_tbl_logs_types1`
    FOREIGN KEY (`id_log_type`)
    REFERENCES `mydb`.`tbl_logs_types` (`id_log_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
ALTER table tbl_students MODIFY COLUMN career varchar(60);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- PROCEDURES
CREATE OR REPLACE PROCEDURE `sp_add_user`(
        IN p_gender_id INT, 
        IN p_soft_delete_options_id INT,
        IN p_first_name VARCHAR(60),
        IN p_last_name VARCHAR(60),
        IN p_email VARCHAR(80),
        IN p_password VARCHAR(250)
)
  INSERT INTO `tbl_users` (
          gender_id, 
          soft_delete_options_id,
          first_name,
          last_name,
          email,          
          password
        ) VALUES (
          p_gender_id, 
          p_soft_delete_options_id,
          p_first_name,
          p_last_name,
          p_email,
          p_password
      )

CREATE OR REPLACE PROCEDURE `sp_add_master`(IN p_role VARCHAR(60), IN p_salary DECIMAL(8,2))
  INSERT INTO `tbl_masters`
        (
              master_id, 
              role, 
              salary
          ) VALUES 
          (
              (SELECT (`AUTO_INCREMENT` - 1)  AS master_id FROM  INFORMATION_SCHEMA.TABLES 
              WHERE TABLE_SCHEMA = 'crud-poo-mvc' AND TABLE_NAME = 'tbl_users'), 
              p_role, 
              p_salary
          )

CREATE OR REPLACE PROCEDURE `sp_add_student`(IN p_career VARCHAR(60), IN p_average DECIMAL(3,1))
  INSERT INTO `tbl_students`
        (
              student_id, 
              career, 
              average
          ) VALUES 
          (
              (SELECT (`AUTO_INCREMENT` - 1)  AS student_id FROM  INFORMATION_SCHEMA.TABLES 
              WHERE TABLE_SCHEMA = 'crud-poo-mvc' AND TABLE_NAME = 'tbl_users'), 
              p_career, 
              p_average
          )

-- INSERTS
INSERT INTO `tbl_genders` (`gender_id`, `gender_name`, `abrev`) VALUES (NULL, 'Femenino', 'F'), (NULL, 'Masculino', 'M'), (NULL, 'Otro', 'O')

INSERT INTO `tbl_soft_delete_options` (`id`, `soft_delete_option`) VALUES (NULL, 'No SoftDelete'), (NULL, 'SoftDelete para Usuarios'), (NULL, 'SoftDelete para Admins'), (NULL, 'SoftDelete para Devs')