-- MySQL Script generated by MySQL Workbench
-- Mon Jun 15 01:01:13 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TBL_USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TBL_USUARIOS` (
  `ID_USUARIO` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE_USUARIO` VARCHAR(45) NOT NULL,
  `APELLIDO_USUARIO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_USUARIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_COMENTARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_COMENTARIOS` (
  `ID_COMENTARIOS` INT NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` INT NOT NULL,
  `COMENTARIO` VARCHAR(45) NOT NULL,
  `FECHA_HORA_COMENTARIO` DATE NOT NULL,
  PRIMARY KEY (`ID_COMENTARIOS`),
  INDEX `fk_TB_COMENTARIOS_TBL_USUARIOS_idx` (`ID_USUARIO` ASC) VISIBLE,
  CONSTRAINT `fk_TB_COMENTARIOS_TBL_USUARIOS`
    FOREIGN KEY (`ID_USUARIO`)
    REFERENCES `mydb`.`TBL_USUARIOS` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
